### ISSUE TITLE
Checklist of function from JS source

### ISSUE THREAD

**Issue by Foxboron** [VerbalExpressions/implementation#1]
These are the functions that need documentation if we consider the original JS version as the refference.
- [ ] add
- [ ] startOfLine
- [ ] endOfLine
- [ ] then
- [ ] find
- [ ] maybe
- [ ] anything
- [ ] anythingBut
- [ ] something
- [ ] somethingBut
- [ ] replace
- [ ] lineBreak
- [ ] br (shorthand for lineBreak)
- [ ] tab
- [ ] word
- [ ] anyOf
- [ ] any (shorthand for anyOf)
- [ ] range
- [ ] withAnyCase
- [ ] stopAtFirst
- [ ] searchOneLine
- [ ] multiple
- [ ] or
- [ ] begindCapture
- [ ] endCapture

**Comment by metal3d** [comment]
We can create a wiki page with explanation

**Comment by Foxboron** [comment]
Should maybe agree on a way to document each function, maybe add a refference implementation?

**Comment by metal3d** [comment]
I just made a wikipage:
https://github.com/VerbalExpressions/implementation/wiki/List-of-methods-to-implement

I'm currently working on

**Comment by metal3d** [comment]
It could be nice that others managers take a look on pages and comments/append some discussion :)

**Comment by crawfordcomeaux** [comment]
I'm thinking a description for each with a table indicating which implementations supports them. Example: JavaScript doesn't natively support look-behind, so unless a non-native hack is added, it's likely other langs will have something for it if they don't already.

**Comment by es** [comment]
So kind of what MDN does only instead of browsers we'd have languages? That sounds like a good idea :+1: 
I think we should add examples to each method as well.

**Comment by metal3d** [comment]
I agree with you, table with lang and possible hack implementation is very interessing.

**Comment by crawfordcomeaux** [comment]
For inspiration: http://hyperpolyglot.org/scripting

**Comment by metal3d** [comment]
@crawfordcomeaux nice, I will try to do this page this afternoon (in France, it's in 2-3 hours)
