### ISSUE TITLE
Question about maintainer ownership

### ISSUE THREAD

**Issue by lukewestby** [VerbalExpressions/implementation#11]
I'm curious since these libraries are very clearly ports of the original library to what extent I have ownership of the elm-verbal-expressions repo specifically, so that I could add a code of conduct of my choosing, for example.

**Comment by whackashoe** [comment]
It would be my understanding that unless you have given up maintainer status you are in control of your repo. I've always operated under the presumption this group is merely a way for the ports to be easily found. 

On a side note: do you really need a coc? They are basically unenforceable on github + I don't think there is really many (any?) examples of people behaving badly in the discussions regarding verbalexpressions. Something about an easy regex builder doesn't attract too many assholes :smile:

**Comment by lukewestby** [comment]
@whackashoe thanks for your response! Makes sense.

Regarding whether a CoC is needed, it's not a concern over this project or its current participants at all, y'all are excellent. Elm seems to be at a critical stage in its community growth where emphasizing inclusivity is paramount, and adding a CoC to Elm projects is one of many ways to do that. It's unlikely that an incident would occur on elm-verbal-expressions, but that's hard to guarantee forever and in the mean time it sends a positive message about the language and its community. I would make sure the scope of the document is clearly defined to be the elm-verbal-expressions repo as well.
