### ISSUE TITLE
How can a new implementation be added to the organization?

### ISSUE THREAD

**Issue by zsmb13** [VerbalExpressions/implementation#14]
I've implemented VerbalExpressions in Kotlin, and I'd like to add it to the rest of the implementations. I'm just wondering what the process is for this, since I haven't found any information about it.

The repo can be found here: [KotlinVerbalExpressions](https://github.com/zsmb13/KotlinVerbalExpressions).

**Comment by mihai-vlc** [comment]
You should now have write access to https://github.com/VerbalExpressions/KotlinVerbalExpressions

Please let me know if I can help with anything else.

**Comment by zsmb13** [comment]
Oh, thank you! Should I just commit the current state of the project there as it is right now? Is there any way to transfer it without losing the commit history?

I can't use the Transfer option under the repository settings without having rights to create a new repository under the organization, as it won't let me move it into this existing one.

**Comment by mihai-vlc** [comment]
you should be able to add the new repo as a second remote.
Something like:
```
git remote add veorigin https://github.com/VerbalExpressions/KotlinVerbalExpressions.git
git push -u veorigin master
```
This should preserve the commit history.

If you have trouble with this I can give you admin rights to transfer the repo.
Just let me know.

**Comment by zsmb13** [comment]
Okay, I understand what I should be doing, but I'm getting this error:

>remote: Permission to VerbalExpressions/KotlinVerbalExpressions.git denied to zsmb13.
fatal: unable to access 'https://github.com/VerbalExpressions/KotlinVerbalExpressions.git/': The requested URL returned error: 403

I've already tried logging out and back in to GitHub locally with this account.

**Comment by mihai-vlc** [comment]
Can you try now please ?

**Comment by zsmb13** [comment]
Still the same.

**Comment by mihai-vlc** [comment]
Third time is a charm ;)
The permissions were lost when I renamed the repo.
It should be fine now.

**Comment by zsmb13** [comment]
Success! Thanks :)

**Comment by whackashoe** [comment]
You should be able to do something like `git remote add upstream
https://github.com/VerbalExpressions/KotlinVerbalExpressions` then `git
push upstream master` ---- you can change upstream to whatever you want.
Alternatively remove the origin remote then do the above with
s/upstream/origin if that's burned into memory like it is for me :)

**Comment by whackashoe** [comment]
Oops, email issue here stuff loaded late - ignore :)
