### ISSUE TITLE
Add DenoVerbalExpressions

### ISSUE THREAD

**Issue by shawnthehumble** [VerbalExpressions/implementation#15]
Deno 1.0 was recently announced.  I ported the JSVerbalExpressions over.  Mainly, I had to make it Strict TypeScript compliant and convert the tests into the core Deno testing framework and add the mod.ts .  You can view it here:  https://github.com/evosland/DenoRegularExpressions .

I didn't call it TsVerbalExpressions because it's specific to Deno and depends on some of its internals.  I didn't write anything new, however.  It's really a fixup of JavaScript version.

**Comment by mihai-vlc** [comment]
I created a repository here: https://github.com/VerbalExpressions/DenoVerbalExpressions

You should have push permissions to it.
Please reopen this if you have any issues.
