### ISSUE TITLE
http://verbalexpressions.github.io/ is empty

### ISSUE THREAD

**Issue by SignpostMarv** [VerbalExpressions/implementation#9]
Noticing some readmes directing people to find a list of implementations; site is empty.

**Comment by jehna** [comment]
<img width="766" alt="screen shot 2016-01-21 at 22 23 02" src="https://cloud.githubusercontent.com/assets/2676795/12493403/8fd8b778-c08d-11e5-83c6-e71d6efd8a08.png">

**Comment by jehna** [comment]
Sounds like a problem at github

**Comment by jehna** [comment]
Yep Github is the one having the issue:

<img width="645" alt="screen shot 2016-01-21 at 22 25 46" src="https://cloud.githubusercontent.com/assets/2676795/12493511/f9ed78e2-c08d-11e5-9d83-ccb7c94143db.png">

Source: https://status.github.com/

**Comment by jehna** [comment]
Closing this issue since GitHub Pages are up&running again
